"""empty message

Revision ID: 3dcee28b5383
Revises: e3ffea70567c
Create Date: 2020-10-20 11:16:30.328677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcee28b5383'
down_revision = 'e3ffea70567c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_category'), 'category', ['category'], unique=True)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_skill'), 'skill', ['skill'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_skill'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_category_category'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
