"""empty message

Revision ID: f430512a5d94
Revises: 3dcee28b5383
Create Date: 2020-10-20 18:49:40.781539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f430512a5d94'
down_revision = '3dcee28b5383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('categoryid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skill', 'category', ['categoryid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_column('skill', 'categoryid')
    # ### end Alembic commands ###
